### ISSUE TITLE
最新のChromeで縦書き表示になりません

### ISSUE THREAD

**Issue by Naoto612** [fukamachi/hatenablog-theme-writer#1]
利用OS: Windows 10
ブラウザ (version): Chrome (47.0.2526.106 m)
URL: http://odai.hatenablog.com/
現象 (できるだけ詳しく):
先ほどWriterのテンプレートをインストールさせていただきましたが、最新のChromeで縦書きひょうじされませんでしたのでご報告いたします。なお、同テンプレートのほかの方のブログを見ても横書きでしたので、私のブログ設定ではなさそうです。
Firefox (43.0.3)では縦書きで表示されています。

**Comment by fukamachi** [comment]
現在、MacのChromeで縦書き表示の不具合があるため一時的に横書き表示にしています。WindowsのChromeには同じ問題はないはずですが、CSSではOSを判別することができないためにすべてのOSのChromeで横書き表示になっています。
対応策として切り替え可能なJavaScriptの提供も考えておりますが、まだ手が回っていません。

現象の詳細とChromeチームの対応進捗についてはこちらをご覧ください。
https://code.google.com/p/chromium/issues/detail?id=523691

**Comment by Naoto612** [comment]
早速のご返信ありがとうございました。お忙しい中ご対応をいただいているとのことで恐れ入ります。縦書きでないことで直接的な困難が発生しているわけではないので、のんびりアップデートを待たせていただこうと思います。

2015年12月30日 17:42 Eitaro Fukamachi notifications@github.com:

**Comment by fukamachi** [comment]
https://github.com/fukamachi/hatenablog-theme-writer/commit/a4773d9f566ebd1e9c7490fb7e9fb79e1402b083 で対応済みでした
